[build]
  # Build command - not needed for static site
  command = "echo 'Static site - no build required'"
  
  # Publish directory - where the static files are located
  publish = "public"

[build.environment]
  # Set Node.js version for serverless functions
  NODE_VERSION = "18"

# API proxy redirects
[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

# Redirect rules for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[functions]
  directory = "netlify/functions"

# Environment variables documentation
# Set these in your Netlify dashboard:
# HEROIC_API_KEY = your_heroic_enterprise_api_key